import { uuidV7 } from '../src/lib/uuid.ts'
// UI regression in an isolated local DB; --forms-only checks controls, --account-only checks bank invalidation.
// Run with a dev server using that same test DB and Chrome --remote-debugging-port=9223.
import assert from 'node:assert/strict'
import { randomUUID } from 'node:crypto'
import { mkdir, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import sharp from 'sharp'
import { signInKakao } from '../src/Global/Auth/Backend/index.ts'
import { REFRESH_TOKEN_COOKIE_NAME } from '../src/lib/auth.ts'
import { withWriteTransaction } from '../src/lib/db.ts'
import { BANKS, formatAccountNumber } from '../src/Domain/User/Shared/index.ts'
import { CURRENCIES, CURRENCY_CODES } from '../src/lib/money.ts'

const database = process.env.TEST_DATABASE_URL
assert.ok(database && ['localhost', '127.0.0.1', '[::1]'].includes(new URL(database).hostname), 'TEST_DATABASE_URL must point to an isolated local PostgreSQL database')
assert.ok(new URL(database).pathname.toLowerCase().includes('test'), 'TEST_DATABASE_URL database name must include test')
process.env.DATABASE_URL = database
const origin = process.env.BROWSER_APP_ORIGIN ?? 'http://localhost:3087'
assert.ok(['localhost', '127.0.0.1'].includes(new URL(origin).hostname), 'Browser checks run only against localhost')
const debuggerOrigin = process.env.CHROME_DEBUG_ORIGIN ?? 'http://127.0.0.1:9223'
const artifactDir = process.env.BROWSER_ARTIFACT_DIR ?? join(tmpdir(), 'da-moa-browser-artifacts')
const tab = await (await fetch(`${debuggerOrigin}/json/new?about:blank`, { method: 'PUT' })).json()
const ws = new WebSocket(tab.webSocketDebuggerUrl)
await new Promise((resolve, reject) => { ws.addEventListener('open', resolve, { once: true }); ws.addEventListener('error', reject, { once: true }) })
let nextId = 1
const pending = new Map()
const exceptions = []
const dialogs = []
const apiReads = []
let loseNextExpenseResponse = false
function cdp(method, params = {}) {
  const id = nextId++
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => { pending.delete(id); reject(new Error(`CDP timeout: ${method}`)) }, 30000)
    pending.set(id, { resolve, reject, timer })
    ws.send(JSON.stringify({ id, method, params }))
  })
}
ws.addEventListener('message', event => {
  const message = JSON.parse(event.data)
  if (message.id) {
    const request = pending.get(message.id)
    if (!request) return
    clearTimeout(request.timer); pending.delete(message.id)
    if (message.error) request.reject(new Error(message.error.message)); else request.resolve(message.result)
  }
  if (message.method === 'Network.requestWillBeSent' && message.params.request.method === 'GET') {
    const url = new URL(message.params.request.url)
    if (url.origin === origin && url.pathname.startsWith('/api/')) apiReads.push(`${url.pathname}${url.search}`)
  }
  if (message.method === 'Runtime.exceptionThrown') exceptions.push(message.params.exceptionDetails.exception?.description ?? message.params.exceptionDetails.text)
  if (message.method === 'Page.javascriptDialogOpening') { dialogs.push(message.params.message); void cdp('Page.handleJavaScriptDialog', { accept: true }) }
  if (message.method === 'Fetch.requestPaused') {
    const paused = message.params
    if (loseNextExpenseResponse && paused.request.method === 'POST' && paused.responseStatusCode === 200) {
      loseNextExpenseResponse = false
      void cdp('Fetch.fulfillRequest', { requestId: paused.requestId, responseCode: 503, responseHeaders: [{ name: 'Content-Type', value: 'application/json' }], body: Buffer.from(JSON.stringify({ error: 'transaction_retry', message: '저장 응답을 확인하지 못했어요. 다시 시도해 주세요.' })).toString('base64') })
    } else void cdp('Fetch.continueResponse', { requestId: paused.requestId })
  }
})
async function evaluate(expression, userGesture = false) {
  const result = await cdp('Runtime.evaluate', { expression, userGesture, awaitPromise: true, returnByValue: true })
    .catch(error => { throw new Error(`${error.message}: ${expression.slice(0, 180)}`) })
  if (result.exceptionDetails) throw new Error(result.exceptionDetails.exception?.description ?? result.exceptionDetails.text)
  return result.result.value
}
async function waitFor(expression, label = expression) {
  const deadline = Date.now() + 30000
  while (Date.now() < deadline) {
    try { if (await evaluate(expression)) return } catch (error) { if (!/context|navigation/i.test(error.message)) throw error }
    await new Promise(resolve => setTimeout(resolve, 100))
  }
  const text = await evaluate('document.body.innerText').catch(() => '')
  throw new Error(`Timed out: ${label}\n${text.slice(0, 1800)}`)
}
const hasText = text => `Boolean(document.body?.innerText.includes(${JSON.stringify(text)}))`
async function navigate(path, text) { await cdp('Page.navigate', { url: new URL(path, origin).href }); if (text) await waitFor(hasText(text), text) }
async function assertPageReads(start, groups = false) {
  await new Promise(resolve => setTimeout(resolve, 700))
  const reads = apiReads.slice(start)
  assert.equal(reads[0], '/api/me', 'verify account before fetching page resources')
  assert.equal(reads.filter(path => path === '/api/me').length, 1, `one me read per navigation: ${reads}`)
  if (groups) assert.equal(reads.filter(path => new URL(path, origin).pathname === '/api/groups').length, 1, `one groups read: ${reads}`)
  for (const path of new Set(reads)) assert.equal(reads.filter(read => read === path).length, 1, `one initial resource read: ${path}`)
}
async function click(text) {
  await waitFor(`Array.from(document.querySelectorAll('button')).some(button => button.textContent.trim() === ${JSON.stringify(text)} && !button.disabled && button.getClientRects().length > 0)`, `enabled button ${text}`)
  await evaluate(`Array.from(document.querySelectorAll('button')).find(button => button.textContent.trim() === ${JSON.stringify(text)} && !button.disabled && button.getClientRects().length > 0).click()`)
}
async function fill(selector, value) {
  if (selector === '[name=bankCode]' || selector === '[name=currency]' || selector === '[name=payerId]') {
    await waitFor("Boolean(document.querySelector('.bank-select-trigger') && !document.querySelector('.bank-select-trigger').disabled)")
    await evaluate("document.querySelector('.bank-select-trigger').click()")
    await waitFor("Boolean(document.querySelector('.bank-sheet[open]'))")
    await evaluate(`document.querySelector('[data-value="${value}"]').click()`)
    await waitFor("!document.querySelector('.bank-sheet[open]')")
    return
  }
  await waitFor(`Array.from(document.querySelectorAll(${JSON.stringify(selector)})).some(element => ['INPUT', 'SELECT', 'TEXTAREA'].includes(element.tagName) && !element.disabled && element.getClientRects().length > 0)`, `input ${selector}`)
  await evaluate(`(() => { const element = Array.from(document.querySelectorAll(${JSON.stringify(selector)})).find(element => ['INPUT', 'SELECT', 'TEXTAREA'].includes(element.tagName) && element.getClientRects().length > 0); if (!element) throw new Error('Input missing'); const setter = Object.getOwnPropertyDescriptor(element.tagName === 'SELECT' ? HTMLSelectElement.prototype : HTMLInputElement.prototype, 'value').set; setter.call(element, ${JSON.stringify(value)}); element.dispatchEvent(new Event('input', {bubbles:true})); element.dispatchEvent(new Event('change', {bubbles:true})); })()`)
}
async function setSession(session) {
  await cdp('Network.clearBrowserCookies')
  await cdp('Network.setCookies', { cookies: [
    { name: REFRESH_TOKEN_COOKIE_NAME, value: session.refreshToken, url: origin, path: '/api/auth', httpOnly: true, sameSite: 'Lax' },
  ] })
  const script = await cdp('Page.addScriptToEvaluateOnNewDocument', { source: `localStorage.setItem('da_moa_access', ${JSON.stringify(session.accessToken)})` })
  await cdp('Page.navigate', { url: origin })
  await waitFor(`location.origin === ${JSON.stringify(origin)} && document.readyState === 'complete'`)
  await cdp('Page.removeScriptToEvaluateOnNewDocument', { identifier: script.identifier })
}
async function api(session, path, method = 'GET', body) {
  const response = await fetch(`${origin}${path}`, { method, headers: { Origin: origin, Authorization: `Bearer ${session.accessToken}`, 'Content-Type': 'application/json', 'Idempotency-Key': method === 'POST' && path === '/api/groups' ? uuidV7() : randomUUID() }, body: body === undefined ? undefined : JSON.stringify(body) })
  const result = await response.json()
  assert.ok(response.ok, `${method} ${path}: ${response.status} ${result.message ?? ''}`)
  return result.data ?? result
}
const runId = randomUUID()
const settlementAmountMinor = 13593n
async function user(label, number, onboarding = false, profileImageUrl = null) {
  const subject = `browser-${runId}-${label}`
  const profile = { displayName: `검증 ${label}`, email: null, profileImageUrl }
  const limited = await signInKakao(subject, profile)
  if (onboarding) return { subject, session: limited }
  // The TEST_DATABASE_URL guard above confines this legacy fixture to the isolated test database.
  await withWriteTransaction(async client => {
    const result = await client.query(`UPDATE users SET bank_name=$2, account_number=$3, account_holder=$4,
      bank_updated_at=created_at, onboarding_completed_at=created_at
      WHERE id=$1 AND provider='kakao' AND provider_subject=$5 AND onboarding_completed_at IS NULL`,
    [limited.userId, `${label}은행`, number, profile.displayName, subject])
    assert.equal(result.rowCount, 1)
  })
  const session = await signInKakao(subject, profile)
  assert.equal(session.purpose, 'app')
  return { subject, session }
}

try {
  await cdp('Page.enable'); await cdp('Page.bringToFront'); await cdp('Runtime.enable'); await cdp('Network.enable')
  await cdp('Fetch.enable', { patterns: [{ urlPattern: `${origin}/api/rounds/*/expenses`, requestStage: 'Response' }] })
  await cdp('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true })
  await cdp('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'no-preference' }] })
  if (process.argv.includes('--account-only')) {
    const member = await user('계좌 재조회', '001234567890')
    await setSession(member.session)
    const hold = await cdp('Page.addScriptToEvaluateOnNewDocument', { source: `
      window.__bankInvalidations = [];
      const NativeSocket = window.WebSocket;
      window.WebSocket = class extends NativeSocket {
        constructor(...args) {
          super(...args);
          if (new URL(args[0], location.href).pathname !== '/realtime') return;
          window.__bankSocket = this;
          this.addEventListener('message', event => {
            const data = JSON.parse(event.data);
            if (data.type === 'invalidate' && data.keys.includes('me')) {
              event.stopImmediatePropagation();
              window.__bankInvalidations.push({ socket: this, data: event.data });
            }
          });
        }
      };
    ` })
    await navigate('/home/account', '내 정보')
    await waitFor('window.__bankSocket?.readyState === WebSocket.OPEN')
    await new Promise(resolve => setTimeout(resolve, 700))
    await click('계좌 수정하기')
    await fill('[name=accountNumber]', '94160201358511')
    await fill('[name=bankCode]', '004')
    await fill('[name=accountHolder]', '수정 검증')
    const reads = apiReads.length
    await click('계좌 저장')
    await waitFor(hasText('계좌를 저장했어요.'))
    await waitFor('window.__bankInvalidations.length === 1')
    await new Promise(resolve => setTimeout(resolve, 700))
    assert.equal(apiReads.length, reads, 'bank PUT must not trigger any GET before invalidation delivery')
    assert.equal(await evaluate("document.querySelector('.account-bank-toggle').disabled"), true, 'wait for the saved version before reopening the editor')
    await evaluate("window.__bankInvalidations.splice(0).forEach(({ socket, data }) => socket.onmessage(new MessageEvent('message', { data })))")
    await waitFor("document.querySelector('.account-details').textContent.includes('941602-01-358511')")
    await new Promise(resolve => setTimeout(resolve, 700))
    assert.deepEqual(apiReads.slice(reads), ['/api/me'], 'one me GET after WebSocket invalidation')
    await click('계좌 수정하기')
    assert.equal(await evaluate("document.querySelector('[name=accountNumber]').value"), '941602-01-358511')
    assert.deepEqual(exceptions, [])
    await cdp('Page.removeScriptToEvaluateOnNewDocument', { identifier: hold.identifier })
    console.log('PASS bank PUT triggers no GET; WebSocket invalidation triggers one me GET and refreshes the form')
    ws.close()
    await fetch(`${debuggerOrigin}/json/close/${tab.id}`)
    process.exit(0)
  }
  if (process.argv.includes('--invites-only')) {
    const owner = await user('초대 생성자', '001234567890')
    const participant = await user('초대 참여자', '002234567890')
    const group = await api(owner.session, '/api/groups', 'POST', { name: `초대 검증 ${runId}` })
    const invite = await api(owner.session, `/api/groups/${group.id}/invites`, 'POST', {})
    await setSession(participant.session)
    await navigate(invite.sharePath, '초대 수락하고 참여하기')
    const acceptReads = apiReads.length
    await click('초대 수락하고 참여하기')
    await waitFor(hasText('모임으로 가기'))
    await new Promise(resolve => setTimeout(resolve, 700))
    assert.equal(await evaluate('location.pathname'), invite.sharePath)
    assert.equal(apiReads.length, acceptReads, 'accept POST must not trigger any GET')
    await evaluate("document.querySelector('a.primary-button').click()")
    await waitFor(hasText('현재 멤버 2명'))
    await assertPageReads(acceptReads)
    await setSession(owner.session)
    await navigate('/home/groups', '새 모임 만들기')
    await new Promise(resolve => setTimeout(resolve, 700))
    const other = await user('추가 참여자', '003234567890')
    const invalidationReads = apiReads.length
    await api(other.session, `/api${invite.sharePath}/accept`, 'POST', {})
    await waitFor(hasText('검증 추가 참여자'))
    await new Promise(resolve => setTimeout(resolve, 700))
    assert.equal(apiReads.slice(invalidationReads).filter(path => path === '/api/groups').length, 1, 'one group-list GET after WebSocket invalidation')
    assert.deepEqual(exceptions, [])
    console.log('PASS accept POST triggers no GET; group list reloads once on WebSocket invalidation')
    process.exitCode = 0
    ws.close()
    await fetch(`${debuggerOrigin}/json/close/${tab.id}`)
    process.exit(0)
  }
  await navigate('/login', '첫 가입 온보딩 보기')
  await click('첫 가입 온보딩 보기')
  await waitFor("location.pathname === '/onboarding' && localStorage.getItem('da_moa_access') !== null")
  const loginCookies = (await cdp('Network.getAllCookies')).cookies
  assert.equal(loginCookies.some(cookie => cookie.name === 'da_moa_access'), false)
  assert.ok(loginCookies.some(cookie => cookie.name === REFRESH_TOKEN_COOKIE_NAME && cookie.httpOnly))
  assert.equal(await evaluate("JSON.parse(atob(localStorage.getItem('da_moa_access').split('.')[1].replaceAll('-', '+').replaceAll('_', '/'))).purpose"), 'onboarding')
  console.log('PASS login completion stores Access JWT locally and only Refresh JWT in an HttpOnly cookie')
  const newcomer = await user('신규', '', true)
  await setSession(newcomer.session)
  await navigate('/onboarding', '검증 신규님, 반가워요')
  assert.deepEqual(await evaluate("Array.from(document.querySelectorAll('.onboarding-page button')).filter(button => button.getClientRects().length && !button.classList.contains('bank-select-trigger')).map(button => button.textContent.trim())"), ['저장하기', '다른 카카오 계정으로 로그인', '뒤로가기'])
  await waitFor("Boolean(document.querySelector('[name=bankCode]'))")
  assert.equal(await evaluate("document.querySelectorAll('[name=bankCode], [name=accountNumber], [name=accountHolder]').length"), 3)
  assert.equal(await evaluate("Boolean(document.querySelector('[name=birthDate]'))"), false)
  const newcomerAccount = await api(newcomer.session, '/api/me')
  assert.equal(newcomerAccount.purpose, 'onboarding')
  assert.equal(newcomerAccount.bankAccount, null)
  assert.equal(await evaluate("document.querySelector('.bank-select-trigger').disabled"), true)
  await fill('[name=accountNumber]', '0001234567')
  await fill('[name=accountHolder]', '신규')
  const openingPositions = await evaluate("(() => { document.querySelector('form').requestSubmit(); const sheet = document.querySelector('.bank-sheet'); const animation = sheet.getAnimations()[0]; animation.pause(); animation.currentTime = 0; const start = sheet.getBoundingClientRect().top; animation.finish(); return [start, sheet.getBoundingClientRect().top]; })()", true)
  assert.ok(openingPositions[0] > openingPositions[1], 'bank sheet rises from below the viewport')
  await waitFor("Boolean(document.querySelector('.bank-sheet[open]'))")
  assert.equal(await evaluate("document.querySelectorAll('.bank-tile').length"), BANKS.length)
  await waitFor("Array.from(document.querySelectorAll('.bank-tile img')).length > 0 && Array.from(document.querySelectorAll('.bank-tile img')).every(img => img.complete && img.naturalWidth > 0 && new URL(img.src).pathname.startsWith('/banks/'))", 'all bank logos loaded locally')
  assert.equal(await evaluate("document.querySelector('.bank-sheet').contains(document.activeElement)"), true)
  await cdp('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Tab', code: 'Tab', windowsVirtualKeyCode: 9 })
  await cdp('Input.dispatchKeyEvent', { type: 'keyUp', key: 'Tab', code: 'Tab', windowsVirtualKeyCode: 9 })
  assert.deepEqual(await evaluate("(() => { const focused = document.activeElement; const style = getComputedStyle(focused); return [focused.matches('.bank-tile:focus-visible'), style.outlineStyle, style.borderColor]; })()"), [true, 'none', 'rgb(20, 109, 176)'])
  await cdp('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Escape', code: 'Escape', windowsVirtualKeyCode: 27 })
  const closingPositions = await evaluate("(() => { const sheet = document.querySelector('.bank-sheet'); const animation = sheet.getAnimations().find(animation => !(animation instanceof CSSAnimation)); animation.pause(); animation.currentTime = 0; const remainsOpen = sheet.open; const start = sheet.getBoundingClientRect().top; animation.currentTime = animation.effect.getTiming().duration - 1; const end = sheet.getBoundingClientRect().top; animation.play(); return [remainsOpen, start, end]; })()")
  assert.equal(closingPositions[0], true, 'dialog remains modal during its closing animation')
  assert.ok(closingPositions[2] > closingPositions[1], 'bank sheet descends before closing')
  await cdp('Input.dispatchKeyEvent', { type: 'keyUp', key: 'Escape', code: 'Escape', windowsVirtualKeyCode: 27 })
  await waitFor("!document.querySelector('.bank-sheet[open]')")
  await waitFor("document.activeElement === document.querySelector('.bank-select-trigger')", 'bank trigger focus restored')
  await fill('[name=bankCode]', '004')
  assert.equal(await evaluate("document.querySelector('.bank-select-trigger').textContent"), 'KB국민은행')
  assert.equal(await evaluate("new FormData(document.querySelector('form')).get('bankCode')"), '004')
  await evaluate("document.querySelector('form').requestSubmit()")
  await waitFor("location.pathname.startsWith('/home')")
  const savedAccount = await evaluate("fetch('/api/me', { headers: { Authorization: 'Bearer ' + localStorage.getItem('da_moa_access') } }).then(response => response.json()).then(result => ({ purpose: result.data.purpose, verifiedAt: result.data.bankAccount.verifiedAt }))")
  assert.deepEqual(savedAccount, { purpose: 'app', verifiedAt: null })
  console.log('PASS onboarding saves a manually entered account')
  if (process.argv.includes('--forms-only')) {
    await navigate('/home/groups', '새 모임 만들기')
    await fill('[name=name]', `입력 검증 ${runId}`)
    assert.equal(await evaluate("document.querySelector('[name=name]').closest('.line-field') !== null"), true)
    assert.deepEqual(await evaluate("(() => { const s = getComputedStyle(document.querySelector('[name=name]')); return [s.borderTopWidth, s.borderBottomWidth, s.borderRadius, s.boxShadow] })()"), ['0px', '2px', '0px', 'none'])
    await click('모임 만들기')
    await waitFor("location.pathname.startsWith('/home/groups/')")
    await waitFor(hasText('새 회차 기록 시작'))
    const customGroupId = (await evaluate('location.pathname')).split('/').at(-1)
    assert.equal(await evaluate("document.querySelector('[name=name]').closest('.line-field') !== null"), true)
    assert.equal(await evaluate("document.querySelector('button[type=submit]').disabled"), true)
    await click('초대 링크 만들기')
    await waitFor("Boolean(document.querySelector('input[aria-label=\"공유 링크\"]')?.value)")
    assert.equal(await evaluate(hasText('링크를 받은 사람이 로그인 후 초대를 수락하면 모임에 참여해요.')), false)
    assert.equal(await evaluate("document.querySelector('.copy-link button') !== null"), false)
    const customInvitePath = new URL(await evaluate("document.querySelector('input[aria-label=\"공유 링크\"]').value")).pathname
    const roundPartner = await user('회차 멤버', '00112233', false, `${origin}/logo/da-moa-128px.png`)
    await api(roundPartner.session, `/api${customInvitePath}/accept`, 'POST', {})
    await waitFor(hasText('현재 멤버 2명'))
    await mkdir(artifactDir, { recursive: true })
    for (const width of [320, 390, 1024]) {
      await cdp('Emulation.setDeviceMetricsOverride', { width, height: 844, deviceScaleFactor: 1, mobile: width < 480 })
      await evaluate("document.querySelector('.bank-select-trigger').click()")
      await waitFor("Boolean(document.querySelector('.bank-sheet[open]'))")
      await evaluate("Promise.all(document.querySelector('.bank-sheet').getAnimations().map(animation => animation.finished))")
      assert.equal(await evaluate("document.querySelectorAll('.bank-tile').length"), CURRENCY_CODES.length)
      await waitFor(`Array.from(document.querySelectorAll('.currency-sheet img')).length === ${CURRENCY_CODES.length} && Array.from(document.querySelectorAll('.currency-sheet img')).every(img => img.complete && img.naturalWidth > 0)`)
      assert.deepEqual(await evaluate("Array.from(document.querySelectorAll('.bank-tile span'), item => item.textContent)"), CURRENCY_CODES.map(code => CURRENCIES[code].name))
      assert.deepEqual(await evaluate("[getComputedStyle(document.querySelector('.currency-sheet')).backgroundColor, getComputedStyle(document.querySelector('.currency-sheet .bank-grid')).flexDirection]"), ['rgb(247, 248, 250)', 'column'])
      await waitFor("!document.querySelector('.currency-sheet .bank-grid').dataset.scrolling")
      await waitFor("getComputedStyle(document.querySelector('.currency-sheet .bank-grid'), '::-webkit-scrollbar-thumb').backgroundColor === 'rgba(0, 0, 0, 0)'")
      await evaluate("document.querySelector('.currency-search input').focus(); document.querySelector('.currency-sheet .bank-grid').scrollTop = 80")
      await waitFor("Boolean(document.querySelector('.currency-sheet .bank-grid').dataset.scrolling)")
      assert.deepEqual(await evaluate("(() => { const list = document.querySelector('.currency-sheet .bank-grid'); const track = getComputedStyle(list, '::-webkit-scrollbar-track'); const thumb = getComputedStyle(list, '::-webkit-scrollbar-thumb'); return [getComputedStyle(list).overflowY, track.backgroundColor, track.borderLeftWidth, thumb.backgroundColor, thumb.borderLeftWidth, list.scrollTop > 0]; })()"), ['auto', 'rgba(0, 0, 0, 0)', '0px', 'rgba(107, 118, 132, 0.45)', '2px', true])
      if (width === 1024) {
        const clip = await evaluate("(() => { const list = document.querySelector('.currency-sheet .bank-grid'); const rect = list.getBoundingClientRect(); return { x: Math.floor(rect.right - 10), y: Math.floor(rect.top + (list.scrollTop + list.clientHeight / 2) * list.clientHeight / list.scrollHeight), width: 10, height: 1, scale: 1 }; })()")
        const thumbWidth = async () => {
          const shot = await cdp('Page.captureScreenshot', { format: 'png', clip })
          const { data, info } = await sharp(Buffer.from(shot.data, 'base64')).raw().toBuffer({ resolveWithObject: true })
          return Array.from({ length: info.width }, (_, x) => data[x * info.channels]).filter(red => red < 210).length
        }
        const normalWidth = await thumbWidth()
        assert.ok(normalWidth > 0, 'Scrolling shows the scrollbar thumb')
        await cdp('Input.dispatchMouseEvent', { type: 'mouseMoved', x: clip.x + 5, y: clip.y })
        await waitFor("Boolean(document.querySelector('.currency-sheet .bank-grid').dataset.scrollbarHovered)")
        assert.ok(await thumbWidth() > normalWidth, 'Hover makes the visible scrollbar thumb wider')
        await waitFor("!document.querySelector('.currency-sheet .bank-grid').dataset.scrolling")
        assert.ok(await thumbWidth() > normalWidth, 'Hover keeps the thumb visible after scrolling stops')
        await cdp('Input.dispatchMouseEvent', { type: 'mouseMoved', x: 0, y: 0 })
      }
      await waitFor("!document.querySelector('.currency-sheet .bank-grid').dataset.scrolling")
      await waitFor("(() => { const color = getComputedStyle(document.querySelector('.currency-sheet .bank-grid'), '::-webkit-scrollbar-thumb').backgroundColor; const alpha = Number(color.match(/, ([\\d.]+)\\)$/)?.[1]); return alpha > 0 && alpha < .45; })()", 'Scrollbar thumb fades out')
      await waitFor("getComputedStyle(document.querySelector('.currency-sheet .bank-grid'), '::-webkit-scrollbar-thumb').backgroundColor === 'rgba(0, 0, 0, 0)'")
      await evaluate("document.querySelector('.currency-sheet .bank-grid').scrollTop = 0")
      assert.equal(await evaluate("getComputedStyle(document.querySelector('.currency-sheet img')).borderTopWidth"), '0px')
      assert.equal(await evaluate("document.querySelectorAll('.bank-tile svg').length"), 0)
      assert.equal(await evaluate("getComputedStyle(document.querySelector('.bank-tile[aria-pressed=true]')).backgroundColor"), 'rgb(230, 244, 255)')
      await cdp('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Tab', code: 'Tab', windowsVirtualKeyCode: 9 })
      await cdp('Input.dispatchKeyEvent', { type: 'keyUp', key: 'Tab', code: 'Tab', windowsVirtualKeyCode: 9 })
      assert.deepEqual(await evaluate("(() => { const selected = document.querySelector('.bank-tile[aria-pressed=true]'); selected.focus(); const style = getComputedStyle(selected); return [selected.matches(':focus-visible'), style.outlineStyle, style.backgroundColor, style.borderColor]; })()"), [true, 'none', 'rgb(230, 244, 255)', 'rgb(20, 109, 176)'])
      assert.equal(await evaluate("document.documentElement.scrollWidth <= innerWidth"), true)
      const shot = await cdp('Page.captureScreenshot', { format: 'png' })
      await writeFile(join(artifactDir, `currency-picker-${width}.png`), Buffer.from(shot.data, 'base64'))
      await evaluate("document.querySelector('.bank-sheet-header button').click()")
      await waitFor("!document.querySelector('.bank-sheet[open]')")
    }
    await evaluate("document.querySelector('.bank-select-trigger').click()")
    await waitFor("Boolean(document.querySelector('.bank-sheet[open]'))")
    for (const [search, expected] of [['일본', ['JPY']], ['usd', ['USD']], ['마카오', ['HKD', 'MOP']], ['캄보디아', ['USD', 'KHR']], ['몰디브', ['USD', 'MVR']], ['독일', ['EUR']], ['없는나라', []]]) {
      await fill('.currency-search input', search)
      await waitFor(`document.querySelectorAll('.bank-tile').length === ${expected.length}`)
      assert.deepEqual(await evaluate("Array.from(document.querySelectorAll('.bank-tile'), button => button.dataset.value)"), expected)
    }
    await evaluate("document.querySelector('.bank-sheet-header button').click()")
    await waitFor("!document.querySelector('.bank-sheet[open]')")
    for (const currency of [...CURRENCY_CODES.filter(code => code !== 'USD'), 'USD']) {
      await fill('[name=currency]', currency)
      assert.equal(await evaluate("new FormData(document.querySelector('form')).get('currency')"), currency)
    }
    await evaluate("document.querySelector('form').requestSubmit()")
    assert.equal(await evaluate('location.pathname'), `/home/groups/${customGroupId}`)
    await fill('[name=name]', '통화 입력 검증')
    await click('이 멤버로 기록 시작')
    await waitFor("location.pathname.startsWith('/home/rounds/')")
    const customRoundId = (await evaluate('location.pathname')).split('/').at(-1)
    const customRound = await evaluate(`fetch('/api/rounds/${customRoundId}', { headers: { Authorization: 'Bearer ' + localStorage.getItem('da_moa_access') } }).then(response => response.json()).then(result => result.data)`)
    assert.equal(customRound.name, '통화 입력 검증')
    assert.equal(customRound.currency, 'USD')
    await click('지출 추가')
    await fill('[name=description]', '지출 입력 검증')
    await fill('[name=amount]', '10.05')
    await evaluate("document.querySelector('input[type=radio][value=CUSTOM]').click()")
    await evaluate("document.querySelectorAll('#expense-editor input[name=participantIds]').forEach(input => input.click())")
    await fill(`[name="customAmount:${newcomer.session.userId}"]`, '4.01')
    await fill(`[name="customAmount:${roundPartner.session.userId}"]`, '6.03')
    assert.equal(await evaluate("document.querySelectorAll('#expense-editor .line-field input').length"), 4)
    assert.equal(await evaluate("Array.from(document.querySelectorAll('#expense-editor .line-field input')).every(input => { const style = getComputedStyle(input); return style.borderTopWidth === '0px' && style.borderBottomWidth === '2px' && style.borderRadius === '0px' && style.boxShadow === 'none'; })"), true)
    assert.equal(await evaluate(hasText('부담할 사람을 선택하고 각자의 부담금을 입력해 주세요. 부담금 합계는 총 금액과 같아야 해요.')), false)
    for (const width of [320, 390, 1024]) {
      await cdp('Emulation.setDeviceMetricsOverride', { width, height: 844, deviceScaleFactor: 1, mobile: width < 480 })
      await evaluate("document.querySelector('.bank-select-trigger').click()")
      await waitFor("Boolean(document.querySelector('.bank-sheet[open]'))")
      await evaluate("Promise.all(document.querySelector('.bank-sheet').getAnimations().map(animation => animation.finished))")
      assert.equal(await evaluate("document.querySelectorAll('.bank-tile .participant-avatar').length"), 2)
      await waitFor(`Boolean(document.querySelector('[data-value="${roundPartner.session.userId}"] img')?.naturalWidth)`)
      assert.equal(await evaluate(`document.querySelector('[data-value="${roundPartner.session.userId}"] img').src`), `${origin}/logo/da-moa-128px.png`)
      assert.equal(await evaluate("document.documentElement.scrollWidth <= innerWidth && document.querySelector('.bank-sheet').scrollWidth <= document.querySelector('.bank-sheet').clientWidth"), true)
      const shot = await cdp('Page.captureScreenshot', { format: 'png' })
      await writeFile(join(artifactDir, `payer-picker-${width}.png`), Buffer.from(shot.data, 'base64'))
      await evaluate("document.querySelector('.bank-sheet-header button').click()")
      await waitFor("!document.querySelector('.bank-sheet[open]')")
    }
    await fill('[name=payerId]', roundPartner.session.userId)
    await waitFor("Boolean(document.querySelector('.bank-select-value img')?.naturalWidth)")
    assert.equal(await evaluate("document.querySelector('.bank-select-value img').src"), `${origin}/logo/da-moa-128px.png`)
    await click('지출 저장')
    await waitFor(hasText('부담금 합계가 총 금액과 일치해야 해요'))
    await fill(`[name="customAmount:${roundPartner.session.userId}"]`, '6.04')
    await click('지출 저장')
    await waitFor("!document.querySelector('#expense-editor')")
    const savedExpense = await evaluate(`fetch('/api/rounds/${customRoundId}', { headers: { Authorization: 'Bearer ' + localStorage.getItem('da_moa_access') } }).then(response => response.json()).then(result => result.data.expenses[0])`)
    assert.equal(savedExpense.description, '지출 입력 검증')
    assert.equal(savedExpense.amountMinor, '1005')
    assert.equal(savedExpense.payerId, roundPartner.session.userId)
    assert.equal(savedExpense.splitMode, 'CUSTOM')
    assert.deepEqual(savedExpense.shares.map(share => share.assignedAmountMinor).sort(), ['401', '604'])
    assert.equal(await evaluate(hasText('지금까지 기록한 지출 내역을 기반으로 한 예상치예요')), false)
    await click('수정')
    await waitFor("Boolean(document.querySelector('#expense-editor [name=payerId]'))")
    assert.equal(await evaluate("document.querySelector('[name=payerId]').value"), roundPartner.session.userId)
    assert.equal(await evaluate("document.querySelector('[name=amount]').value"), '10.05')
    await cdp('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true })
    await evaluate("document.querySelector('#expense-editor').scrollIntoView({ block: 'start' })")
    const expenseShot = await cdp('Page.captureScreenshot', { format: 'png' })
    await writeFile(join(artifactDir, 'expense-inputs.png'), Buffer.from(expenseShot.data, 'base64'))
    await click('닫기')
    await click('정산 확정')
    await click('전송 안내 확인')
    await waitFor("Boolean(document.querySelector('.copy-link input')?.value)")
    assert.equal(await evaluate("document.querySelector('.copy-link input').value"), `${origin}/settlements/${customRoundId}`)
    assert.equal(await evaluate("Boolean(document.querySelector('.copy-link button'))"), false)
    assert.equal(await evaluate(hasText('본인의 최종 안내예요. 실제 송금은 직접 진행해 주세요.')), false)
    assert.equal(await evaluate(hasText('링크를 통해 접속하면 자신이 보낼 금액과 계좌번호, 자신이 받을 금액을 볼 수 있어요.')), false)
    assert.equal(await evaluate("(() => { const input = document.querySelector('.copy-link input'); input.focus(); return input.selectionStart === 0 && input.selectionEnd === input.value.length; })()"), true)
    const secondReceiver = await user('두 번째 수취인', '00112244')
    await api(secondReceiver.session, `/api${customInvitePath}/accept`, 'POST', {})
    const senderId = newcomer.session.userId
    const pendingRound = await api(roundPartner.session, `/api/groups/${customGroupId}/rounds`, 'POST', { name: '남은 송금 금액 검증', currency: 'USD', participantIds: [senderId, roundPartner.session.userId, secondReceiver.session.userId] })
    const pendingRoundId = pendingRound.roundId
    let pendingVersion = pendingRound.version
    for (const [receiver, amount] of [[roundPartner, '6.00'], [secondReceiver, '4.00']]) {
      const result = await api(roundPartner.session, `/api/rounds/${pendingRoundId}/expenses`, 'POST', { description: '수취인별 지출', amount, payerId: receiver.session.userId, splitMode: 'CUSTOM', customShares: [{ userId: senderId, amount }], expectedVersion: pendingVersion })
      pendingVersion = result.version
    }
    for (const command of ['confirm', 'send']) {
      const result = await api(roundPartner.session, `/api/rounds/${pendingRoundId}/${command}`, 'POST', { expectedVersion: pendingVersion })
      pendingVersion = result.version
    }
    await navigate(`/settlements/${pendingRoundId}`, '내가 보낼 금액')
    const sendingAmount = "document.querySelector('.settlement-animated-money')?.getAttribute('aria-label')?.replace(/\\D/g, '')"
    await waitFor(`${sendingAmount} === '1000'`)
    // Receiver updates must change the sender's open screen through realtime invalidation.
    await api(roundPartner.session, `/api/rounds/${pendingRoundId}/settlement-check`, 'POST', { checked: true, senderId, expectedVersion: pendingVersion })
    await waitFor(`${sendingAmount} === '400'`, 'one recipient confirmation subtracts only that transfer')
    assert.equal(await evaluate("document.querySelectorAll('section.stack > article.domain-card').length"), 1)
    await api(roundPartner.session, `/api/rounds/${pendingRoundId}/settlement-check`, 'POST', { checked: false, senderId, expectedVersion: pendingVersion })
    await waitFor(`${sendingAmount} === '1000'`, 'confirmation reversal restores the sending amount')
    assert.equal(await evaluate("document.querySelectorAll('section.stack > article.domain-card').length"), 2)
    await api(roundPartner.session, `/api/rounds/${pendingRoundId}/settlement-check`, 'POST', { checked: true, expectedVersion: pendingVersion })
    await api(secondReceiver.session, `/api/rounds/${pendingRoundId}/settlement-check`, 'POST', { checked: true, expectedVersion: pendingVersion })
    await waitFor(`${sendingAmount} === '000'`, 'all confirmations leave zero to send')
    assert.equal(await evaluate("document.querySelectorAll('section.stack > article.domain-card').length"), 0)
    await navigate(`/settlements/${pendingRoundId}`, '내가 보낼 금액')
    await waitFor(`${sendingAmount} === '000'`, 'confirmed amount remains zero after reload')
    assert.equal(await evaluate(`fetch('/api/rounds/${pendingRoundId}/settlement', { headers: { Authorization: 'Bearer ' + localStorage.getItem('da_moa_access') } }).then(response => response.json()).then(result => result.data.balanceMinor)`), '1000')
    await cdp('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true })
    await navigate('/home/account', '내 정보')
    await click('계좌 수정하기')
    assert.equal(await evaluate("document.querySelector('[name=accountNumber]').value"), formatAccountNumber('004', '0001234567'))
    await fill('[name=accountNumber]', '3333123456789')
    await fill('[name=bankCode]', '090')
    assert.equal(await evaluate("document.querySelector('[name=accountNumber]').value"), '3333-12-3456789')
    await fill('[name=accountHolder]', '수정 검증')
    await mkdir(artifactDir, { recursive: true })
    for (const width of [320, 390, 1024]) {
      await cdp('Emulation.setDeviceMetricsOverride', { width, height: 844, deviceScaleFactor: 1, mobile: width < 480 })
      assert.equal(await evaluate("document.documentElement.scrollWidth <= innerWidth"), true)
      await evaluate("document.querySelector('.bank-select-trigger').click()")
      await waitFor("Boolean(document.querySelector('.bank-sheet[open]'))")
      await evaluate("Promise.all(document.querySelector('.bank-sheet').getAnimations().map(animation => animation.finished))")
      assert.equal(await evaluate("getComputedStyle(document.querySelector('.bank-grid')).gridTemplateColumns.split(' ').length"), 3)
      assert.equal(await evaluate("document.querySelector('.bank-sheet').scrollWidth <= document.querySelector('.bank-sheet').clientWidth"), true)
      assert.equal(await evaluate("document.querySelector('.bank-sheet-header').getBoundingClientRect().top >= document.querySelector('.bank-sheet').getBoundingClientRect().top"), true)
      const shot = await cdp('Page.captureScreenshot', { format: 'png' })
      await writeFile(join(artifactDir, `bank-picker-${width}.png`), Buffer.from(shot.data, 'base64'))
      await evaluate("document.querySelector('.bank-sheet-header button').click()")
      await waitFor("!document.querySelector('.bank-sheet[open]')")
    }
    await cdp('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'reduce' }] })
    assert.deepEqual(await evaluate("(() => { document.querySelector('.bank-select-trigger').click(); const sheet = document.querySelector('.bank-sheet'); const count = sheet.getAnimations().length; document.querySelector('.bank-sheet-header button').click(); return [count, sheet.open]; })()"), [0, false])
    await cdp('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'no-preference' }] })
    await click('계좌 저장')
    await waitFor(hasText('계좌를 저장했어요.'))
    await click('계좌 수정하기')
    assert.deepEqual(await evaluate("['bankCode', 'accountNumber', 'accountHolder'].map(name => document.querySelector(`[name=${name}]`).value)"), ['090', '3333-12-3456789', '수정 검증'])
    const shot = await cdp('Page.captureScreenshot', { format: 'png' })
    await writeFile(join(artifactDir, 'form-inputs.png'), Buffer.from(shot.data, 'base64'))
    for (const [path, heading] of [['/home/groups', '새 모임 만들기'], ['/home/history', '정산 기록']]) {
      await navigate(path, heading)
      await waitFor(`location.pathname === ${JSON.stringify(path)} && Boolean(document.querySelector('.round-search-bar input'))`)
      assert.deepEqual(await evaluate("(() => { const input = document.querySelector('.round-search-bar input'); const bar = input.parentElement; const shadow = getComputedStyle(bar).boxShadow; input.focus(); const style = getComputedStyle(bar); return [getComputedStyle(input).outlineStyle, style.outlineStyle, style.boxShadow === shadow, style.borderColor]; })()"), ['none', 'none', true, 'rgb(93, 196, 252)'])
    }
    for (const [currency, amount, input, display] of [['EUR', '1234.01', '1,234.01', '1,234.01 EUR'], ['VND', '1234', '1,234', '1,234 VND']]) {
      const round = await api(roundPartner.session, `/api/groups/${customGroupId}/rounds`, 'POST', { name: `${currency} 화면 검증`, currency, participantIds: [newcomer.session.userId, roundPartner.session.userId] })
      await navigate(`/home/rounds/${round.id}`, `${currency} 화면 검증`)
      await click('지출 추가')
      await fill('[name=description]', `${currency} 지출`)
      await fill('[name=amount]', amount)
      assert.equal(await evaluate("document.querySelector('[name=amount]').inputMode"), currency === 'VND' ? 'numeric' : 'decimal')
      await click('지출 저장')
      await waitFor("!document.querySelector('#expense-editor')")
      await waitFor(hasText(display))
      await waitFor(`document.querySelector('.round-total-money').textContent === ${JSON.stringify(display)}`)
      await click('수정')
      await waitFor("Boolean(document.querySelector('#expense-editor'))")
      assert.equal(await evaluate("document.querySelector('[name=amount]').value"), input)
      await click('닫기')
    }
    assert.deepEqual(exceptions, [])
    console.log('PASS custom controls: required bank, Escape/focus, group/round creation, currency/payer selection, expense validation/save/edit, settlement sharing/remaining outgoing amounts, account save, search focus, 320/390/1024px layouts')
    console.log(`Browser evidence: ${artifactDir}`)
    ws.close()
    process.exit(0)
  }
  const owner = await user('A', '001111')
  const payer = await user('B', '002222')
  const participant = await user('C', '003333')
  const extraD = await user('D', '004444')
  const extraE = await user('E', '005555')
  await setSession(owner.session)
  await navigate('/home', '함께 쓴 돈, 함께 정리해요')
  console.log('SETUP settlement regression uses legacy account fixtures seeded only in TEST_DATABASE_URL')

  let readStart = apiReads.length
  await navigate('/home/groups', '새 모임 만들기')
  await assertPageReads(readStart, true)
  for (const [path, heading] of [['/home', '함께 쓴 돈, 함께 정리해요'], ['/home/history', '정산 기록'], ['/home/all', '계좌 설정'], ['/home/account', '내 정보'], ['/home/groups', '새 모임 만들기']]) {
    readStart = apiReads.length
    await waitFor(`Boolean(document.querySelector('a[href="${path}"]'))`)
    await evaluate(`document.querySelector('a[href="${path}"]').click()`)
    await waitFor(`location.pathname === '${path}' && ${hasText(heading)}`)
    await assertPageReads(readStart, path === '/home/groups')
  }
  console.log('PASS direct entry and client navigation read me once and each page resource once, including groups and account')
  assert.equal(await evaluate("Boolean(document.querySelector('[name=currency]'))"), false)
  const groupName = `브라우저 검증 ${runId.slice(0, 6)}`
  await fill('[name=name]', groupName)
  await click('모임 만들기')
  await waitFor(hasText('현재 멤버 1명'))
  const groupId = (await evaluate('location.pathname')).split('/').at(-1)
  await click('초대 링크 만들기')
  await waitFor("Boolean(document.querySelector('input[aria-label=\"공유 링크\"]')?.value)")
  const invitePath = new URL(await evaluate("document.querySelector('input[aria-label=\"공유 링크\"]').value")).pathname
  for (const member of [payer, participant, extraD, extraE]) {
    await setSession(member.session)
    await navigate(invitePath, '초대 수락하고 참여하기')
    assert.equal(await evaluate(hasText('기준 통화')), false)
    const acceptReads = apiReads.length
    await click('초대 수락하고 참여하기')
    await waitFor(hasText('모임으로 가기'))
    await new Promise(resolve => setTimeout(resolve, 700))
    assert.equal(await evaluate('location.pathname'), invitePath)
    assert.equal(apiReads.slice(acceptReads).some(path => path === '/api/groups' || path === `/api/groups/${groupId}`), false, 'accept POST must not fetch group data')
    await evaluate("document.querySelector('a.primary-button').click()")
    await waitFor(`location.pathname === '/home/groups/${groupId}' && ${hasText('현재 멤버')}`)
  }
  await waitFor("document.querySelectorAll('.member-picker .check-row').length === 5")
  assert.equal(await evaluate("document.querySelector('.member-picker .check-row:first-of-type input')?.value"), extraE.session.userId)
  assert.equal(await evaluate("document.querySelector('.member-picker .check-row:first-of-type')?.textContent.includes('검증 E (회차 생성자 · 필수)')"), true)
  assert.equal(await evaluate(`Array.from(document.querySelectorAll('.member-picker .check-row')).find(row => row.querySelector('input')?.value === ${JSON.stringify(owner.session.userId)})?.textContent.includes('회차 생성자')`), false)
  await setSession(owner.session)
  readStart = apiReads.length
  await navigate(`/home/groups/${groupId}`, '현재 멤버 5명')
  await assertPageReads(readStart)
  assert.equal(apiReads.slice(readStart).filter(path => path === `/api/groups/${groupId}`).length, 1)
  assert.equal(apiReads.slice(readStart).some(path => path === `/api/groups/${groupId}/members`), false)

  assert.equal(await evaluate("document.querySelectorAll('[aria-label=\"현재 멤버 요약\"] > li').length"), 4)
  assert.equal(await evaluate("document.querySelector('[aria-label=\"현재 멤버 요약\"] > li:first-child')?.textContent.includes('검증 A') && document.querySelector('[aria-label=\"현재 멤버 요약\"] > li:first-child')?.textContent.includes('모임 생성자')"), true)
  assert.equal(await evaluate("Boolean(document.querySelector('button[aria-label=\"현재 멤버 전체 보기\"][aria-haspopup=\"dialog\"][aria-controls=\"group-members-dialog\"]'))"), true)
  await click('더보기')
  await waitFor("Boolean(document.querySelector('dialog#group-members-dialog[open][aria-labelledby=\"group-members-dialog-heading\"]'))")
  assert.equal(await evaluate("document.querySelectorAll('#group-members-dialog [aria-label=\"현재 멤버 전체 목록\"] > li').length"), 5)
  assert.equal(await evaluate("document.querySelector('#group-members-dialog [aria-label=\"현재 멤버 전체 목록\"] > li:first-child')?.textContent.includes('검증 A') && document.querySelector('#group-members-dialog [aria-label=\"현재 멤버 전체 목록\"] > li:first-child')?.textContent.includes('모임 생성자')"), true)
  await evaluate("document.querySelector('button[aria-label=\"현재 멤버 목록 닫기\"]').click()")
  await waitFor("!document.querySelector('#group-members-dialog[open]')")
  assert.equal(await evaluate("document.querySelector('[name=currency]').value"), 'KRW')
  assert.deepEqual(await evaluate("Array.from(document.querySelector('[name=currency]').options, option => option.value)"), CURRENCY_CODES)
  await evaluate(`document.querySelector('input[name=participantIds][value="${extraD.session.userId}"]').click(); document.querySelector('input[name=participantIds][value="${extraE.session.userId}"]').click()`)
  assert.equal(await evaluate("document.querySelectorAll('input[name=participantIds]:checked').length"), 3)
  await fill('[name=name]', '지출과 제외 검증')
  await click('이 멤버로 기록 시작')
  await waitFor(hasText('지출 내역이 없습니다.'))
  const roundId = (await evaluate('location.pathname')).split('/').at(-1)
  assert.equal((await api(owner.session, `/api/rounds/${roundId}`)).currency, 'KRW')
  assert.equal(await evaluate("document.querySelector('.round-total-money')?.getAttribute('aria-label')"), '0원')
  await click('정산 확정')
  await waitFor("document.querySelector('[role=alert]')?.textContent.includes('지출 내역이 없습니다')")
  console.log('PASS group creation, explicit invitations, round creation, and empty-confirm rejection')

  await click('지출 추가')
  await fill('[name=description]', '저녁 식사')
  await fill('[name=amount]', settlementAmountMinor.toString())
  await fill('[name=payerId]', payer.session.userId)
  loseNextExpenseResponse = true
  await click('지출 저장')
  await waitFor(hasText('저장 응답을 확인하지 못했어요.'))
  await click('새로고침')
  await waitFor("document.querySelector('.round-total-money')?.getAttribute('aria-label') === '13,593원' && Array.from(document.querySelectorAll('.round-total-money .settlement-money-digit-changing.roll-up')).some(digit => digit.getAnimations({ subtree: true }).some(animation => animation.playState === 'running'))", 'round total increase digit animation')
  await click('지출 저장')
  await waitFor(hasText('전체 균등 분배'))
  await waitFor("!document.querySelector('.expense-form')")
  assert.equal(await evaluate("Boolean(document.querySelector('.transfer-money .settlement-money-digit')) && document.querySelector('.transfer-money').getAttribute('aria-label').startsWith('예상 ')"), true)
  let firstSavedRound = await api(owner.session, `/api/rounds/${roundId}`)
  assert.equal(firstSavedRound.expenses.length, 1)
  console.log('PASS lost successful write response, refreshed version, same-key retry without duplicate expense')

  await click('지출 추가')
  await fill('[name=description]', '개별 부담금 검증')
  await fill('[name=amount]', '1000')
  await evaluate("document.querySelector('input[type=radio][value=CUSTOM]').click()")
  await evaluate(`document.querySelector('input[name=participantIds][value="${owner.session.userId}"]').click(); document.querySelector('input[name=participantIds][value="${participant.session.userId}"]').click()`)
  await fill(`[name="customAmount:${owner.session.userId}"]`, '300')
  await fill(`[name="customAmount:${participant.session.userId}"]`, '600')
  await click('지출 저장')
  await waitFor(hasText('부담금 합계가 총 금액과 일치해야 해요'))
  assert.equal((await api(owner.session, `/api/rounds/${roundId}`)).version, firstSavedRound.version)
  assert.equal(await evaluate("document.querySelector('[name=amount]').value"), '1,000')
  await fill(`[name="customAmount:${owner.session.userId}"]`, '0')
  await click('지출 저장')
  await waitFor(hasText('부담금은 0보다 큰 금액으로 입력해 주세요.'))
  await fill(`[name="customAmount:${owner.session.userId}"]`, '300')
  await fill(`[name="customAmount:${participant.session.userId}"]`, '700')
  await click('지출 저장')
  await waitFor("!document.querySelector('.expense-form') && document.querySelectorAll('.expense-card').length === 2")
  const customRound = await api(owner.session, `/api/rounds/${roundId}`)
  const customExpense = customRound.expenses.find(expense => expense.description === '개별 부담금 검증')
  assert.equal(customRound.totalMinor, '14593')
  assert.equal(customExpense.splitMode, 'CUSTOM')
  assert.equal(customExpense.amountMinor, '1000')
  assert.deepEqual(Object.fromEntries(customExpense.shares.map(share => [share.userId, share.assignedAmountMinor])), { [owner.session.userId]: '300', [participant.session.userId]: '700' })
  await evaluate(`document.querySelector('#expense-${customExpense.id} summary').click()`)
  assert.equal(await evaluate(`document.querySelector('#expense-${customExpense.id} details').innerText.includes('300원') && document.querySelector('#expense-${customExpense.id} details').innerText.includes('700원')`), true)
  await evaluate(`Array.from(document.querySelectorAll('#expense-${customExpense.id} button')).find(button => button.textContent.trim() === '수정').click()`)
  await waitFor("document.querySelector('input[type=radio][value=CUSTOM]')?.checked")
  assert.equal(await evaluate(`document.querySelector('[name="customAmount:${owner.session.userId}"]').value`), '300')
  assert.equal(await evaluate(`document.querySelector('[name="customAmount:${participant.session.userId}"]').value`), '700')
  await fill(`[name="customAmount:${owner.session.userId}"]`, '400')
  await fill(`[name="customAmount:${participant.session.userId}"]`, '600')
  await cdp('Emulation.setDeviceMetricsOverride', { width: 320, height: 844, deviceScaleFactor: 1, mobile: true })
  assert.equal(await evaluate("document.querySelector('.expense-form').scrollWidth <= document.querySelector('.expense-form').clientWidth"), true)
  await cdp('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true })
  await mkdir(artifactDir, { recursive: true })
  const customClip = await evaluate("(() => { const rect = document.querySelector('.expense-form').getBoundingClientRect(); return { x: rect.left + scrollX, y: rect.top + scrollY, width: rect.width, height: rect.height, scale: 1 }; })()")
  const customScreenshot = await cdp('Page.captureScreenshot', { format: 'png', captureBeyondViewport: true, clip: customClip })
  await writeFile(join(artifactDir, 'custom-split.png'), Buffer.from(customScreenshot.data, 'base64'))
  await click('지출 저장')
  await waitFor("!document.querySelector('.expense-form')")
  const editedCustom = (await api(owner.session, `/api/rounds/${roundId}`)).expenses.find(expense => expense.id === customExpense.id)
  assert.deepEqual(Object.fromEntries(editedCustom.shares.map(share => [share.userId, share.assignedAmountMinor])), { [owner.session.userId]: '400', [participant.session.userId]: '600' })
  await evaluate(`document.querySelector('#expense-${customExpense.id} button.danger-text').click()`)
  await waitFor("document.querySelectorAll('.expense-card').length === 1")
  firstSavedRound = await api(owner.session, `/api/rounds/${roundId}`)
  assert.equal(firstSavedRound.totalMinor, settlementAmountMinor.toString())
  console.log('PASS custom burden amounts match the expense total, reject mismatches and zero, restore on edit, and fit mobile')

  await click('지출 추가')
  await fill('input[name=description]', '버전 충돌 복구')
  await fill('[name=amount]', '10')
  await api(owner.session, `/api/rounds/${roundId}/expenses/${firstSavedRound.expenses[0].id}`, 'PATCH', { description: firstSavedRound.expenses[0].description, expectedVersion: firstSavedRound.version })
  await evaluate("window.__staleAlertSeen = false; window.__staleAlertObserver = new MutationObserver(() => { if (document.querySelector('.expense-form [role=alert]')) window.__staleAlertSeen = true }); window.__staleAlertObserver.observe(document.body, { childList: true, subtree: true })")
  await click('지출 저장')
  await waitFor("!document.querySelector('.expense-form') && document.querySelectorAll('.expense-card').length === 2")
  assert.equal(await evaluate("window.__staleAlertObserver.disconnect(); window.__staleAlertSeen"), false)
  assert.equal((await api(owner.session, `/api/rounds/${roundId}`)).expenses.filter(expense => expense.description === '버전 충돌 복구').length, 1)
  await withWriteTransaction(client => client.query('UPDATE expenses SET created_at=created_at-172800 WHERE id=$1', [firstSavedRound.expenses[0].id]))
  await click('새로고침')
  await waitFor("document.querySelectorAll('#round-expenses > .expense-day-divider').length === 2")
  assert.deepEqual(await evaluate("Array.from(document.querySelectorAll('#round-expenses > .expense-day-divider time'), time => time.dateTime)"), await evaluate("Array.from(new Set(Array.from(document.querySelectorAll('#round-expenses > .expense-day-divider time'), time => time.dateTime)))"))
  assert.equal(await evaluate("document.querySelectorAll('#round-expenses > .expense-day-divider + .expense-card').length"), 2)
  assert.deepEqual(await evaluate("Array.from(document.querySelectorAll('#round-expenses > .expense-card h3'), heading => heading.textContent)"), ['저녁 식사', '버전 충돌 복구'])
  await evaluate("Array.from(document.querySelectorAll('.expense-card')).find(card => card.textContent.includes('버전 충돌 복구')).querySelector('button.danger-text').click()")
  await waitFor("document.querySelectorAll('.expense-card').length === 1")
  console.log('PASS stale expense auto-save and created-day expense dividers')

  await click('지출 추가')
  await fill('input[name=description]', '응답 복구 검증')
  await fill('[name=amount]', '10')
  loseNextExpenseResponse = true
  await click('지출 저장')
  await waitFor(hasText('저장 응답을 확인하지 못했어요.'))
  await fill('[name=amount]', '20')
  await click('지출 저장')
  await waitFor(hasText('이전 요청의 저장 결과를 먼저 확인해야 해요.'))
  await click('이전 요청 확인 후 새로고침')
  await waitFor("!document.querySelector('.expense-form') && document.querySelectorAll('.expense-card').length === 2")
  const recovered = (await api(owner.session, `/api/rounds/${roundId}`)).expenses.filter(expense => expense.description === '응답 복구 검증')
  assert.equal(recovered.length, 1)
  assert.equal(recovered[0].amountMinor, '10')
  await evaluate("Array.from(document.querySelectorAll('.expense-card')).find(card => card.textContent.includes('응답 복구 검증')).querySelector('button.danger-text').click()")
  await waitFor("document.querySelectorAll('.expense-card').length === 1 && Array.from(document.querySelectorAll('.round-total-money .settlement-money-digit-changing.roll-down')).some(digit => digit.getAnimations({ subtree: true }).some(animation => animation.playState === 'running')) && Array.from(document.querySelectorAll('.transfer-money .settlement-money-digit-changing.roll-up')).some(digit => digit.getAnimations({ subtree: true }).some(animation => animation.playState === 'running'))", 'round total decrease and transfer increase digit animations')
  await waitFor("document.querySelectorAll('.expense-card').length === 1")
  console.log('PASS changed pending input recovery and shared round total/transfer digit animations')
  const imagePath = join(tmpdir(), `da-moa-browser-${runId}.png`)
  await writeFile(imagePath, await sharp({ create: { width: 2, height: 2, channels: 3, background: '#369' } }).png().toBuffer())
  await click('영수증 추가')
  await waitFor("Boolean(document.querySelector('dialog[open] input[type=file]'))")
  const fileInput = await cdp('Runtime.evaluate', { expression: "document.querySelector('dialog[open] input[type=file]')" })
  await cdp('DOM.setFileInputFiles', { files: [imagePath], objectId: fileInput.result.objectId })
  await click('선택한 영수증 업로드')
  await waitFor("!document.querySelector('dialog[open]') && Array.from(document.querySelectorAll('button')).some(button => button.textContent.includes('증빙 1 보기'))")
  await evaluate("Array.from(document.querySelectorAll('button')).find(button => button.textContent.includes('증빙 1 보기')).click()")
  await waitFor("Boolean(document.querySelector('.receipt-preview')?.complete)")
  await evaluate("document.querySelector('button[aria-label=\"검증 B 제외\"]').click()")
  await waitFor(hasText('해당 사용자와 연관된 정산이 있습니다.'))
  assert.equal(await evaluate("document.querySelectorAll('.expense-highlight').length"), 1)
  await click('수정')
  await evaluate("document.querySelector('input[type=radio][value=SELECTED]').click()")
  await waitFor("Boolean(document.querySelector('input[name=participantIds]'))")
  await evaluate(`document.querySelector('input[name=participantIds][value="${payer.session.userId}"]').click()`)
  await click('지출 저장')
  await waitFor("!document.querySelector('.expense-form')")
  await evaluate("document.querySelector('button[aria-label=\"검증 B 제외\"]').click()")
  await click('이 사용자 제외하기')
  await waitFor(hasText('제외됨 · 기록 보존'))
  console.log('PASS manual payer, receipt upload/read, exclusion highlight, owner edit, excluded creditor retained')

  await navigate(`/home/groups/${groupId}`, '현재 멤버 5명')
  assert.equal(await evaluate("Array.from(document.querySelectorAll('.check-row')).some(row => row.textContent.includes('검증 B'))"), true)
  await fill('[name=name]', '취소할 두 번째 회차')
  await fill('[name=currency]', 'USD')
  await click('이 멤버로 기록 시작')
  await waitFor(hasText('회차 전체 취소'))
  const secondRoundId = (await evaluate('location.pathname')).split('/').at(-1)
  const [firstRound, secondRound] = await Promise.all([api(owner.session, `/api/rounds/${roundId}`), api(owner.session, `/api/rounds/${secondRoundId}`)])
  assert.equal(firstRound.groupId, secondRound.groupId)
  assert.equal(firstRound.currency, 'KRW')
  assert.equal(secondRound.currency, 'USD')
  assert.equal(await evaluate("Boolean(document.querySelector('[name=currency]'))"), false)
  console.log('PASS one group creates independent KRW and USD rounds with currency selected only at creation')
  await click('회차 전체 취소')
  await waitFor(`location.pathname === '/home/groups/${groupId}' && ${hasText('현재 멤버 5명')}`)
  for (let index = 1; index <= 3; index++) await api(owner.session, `/api/groups/${groupId}/rounds`, 'POST', { name: `목록 검증 ${index}`, currency: 'KRW', participantIds: [owner.session.userId, participant.session.userId] })
  await navigate(`/home/groups/${groupId}`, '목록 검증')
  assert.equal(await evaluate("document.querySelectorAll('[aria-label=\"내가 참여한 회차 요약\"] > a.round-link').length"), 3)
  assert.equal(await evaluate("Boolean(document.querySelector('button[aria-label=\"참여 회차 전체 보기\"][aria-haspopup=\"dialog\"][aria-controls=\"group-rounds-dialog\"]'))"), true)
  assert.equal(await evaluate("Boolean(document.querySelector('button[aria-label=\"내가 참여한 회차 검색\"]'))"), false)
  await evaluate("document.querySelector('button[aria-label=\"참여 회차 전체 보기\"]').click()")
  await waitFor("Boolean(document.querySelector('dialog#group-rounds-dialog[open][aria-labelledby=\"group-rounds-dialog-heading\"]')) && document.querySelectorAll('#group-rounds-dialog [aria-label=\"참여 회차 전체 목록\"] a.round-link').length === 4")
  assert.equal(await evaluate("(() => { const dialog = document.querySelector('#group-rounds-dialog'); const backdrop = getComputedStyle(dialog, '::backdrop'); return getComputedStyle(document.documentElement).overflow === 'hidden' && getComputedStyle(document.body).overflow === 'hidden' && getComputedStyle(dialog).overscrollBehaviorY === 'contain' && backdrop.backdropFilter === 'blur(8px)' && backdrop.backgroundColor === 'rgba(25, 31, 40, 0.58)'; })()"), true)
  assert.equal(await evaluate("Boolean(document.querySelector('#group-rounds-dialog .round-search-bar > svg') && document.querySelector('#group-rounds-dialog .round-search-bar > input[aria-label=\"내가 참여한 회차 검색어\"]'))"), true)
  assert.equal(await evaluate("document.querySelectorAll('#group-rounds-dialog [aria-label=\"회차 상태\"] > button').length === 3 && Array.from(document.querySelectorAll('#group-rounds-dialog [aria-label=\"회차 상태\"] > button')).find(button => button.textContent.trim() === '전체')?.getAttribute('aria-pressed') === 'true'"), true)
  await fill('#group-rounds-dialog input[aria-label="내가 참여한 회차 검색어"]', '목록 검증 1')
  await waitFor("document.querySelectorAll('#group-rounds-dialog [aria-label=\"참여 회차 전체 목록\"] a.round-link').length === 1 && document.querySelector('#group-rounds-dialog [aria-label=\"참여 회차 전체 목록\"]')?.textContent.includes('목록 검증 1')")
  assert.equal(await evaluate("document.querySelectorAll('[aria-label=\"내가 참여한 회차 요약\"] > a.round-link').length"), 3)
  await fill('#group-rounds-dialog input[aria-label="내가 참여한 회차 검색어"]', groupName)
  await waitFor("document.querySelectorAll('#group-rounds-dialog [aria-label=\"참여 회차 전체 목록\"] a.round-link').length === 4")
  await click('정산 종료')
  await waitFor("document.querySelectorAll('#group-rounds-dialog [aria-label=\"참여 회차 전체 목록\"] a.round-link').length === 0 && document.querySelector('#group-rounds-dialog')?.textContent.includes('조건에 맞는 회차가 없어요.')")
  assert.equal(await evaluate("document.querySelectorAll('[aria-label=\"내가 참여한 회차 요약\"] > a.round-link').length"), 3)
  await click('진행 중')
  await waitFor("document.querySelectorAll('#group-rounds-dialog [aria-label=\"참여 회차 전체 목록\"] a.round-link').length === 4")
  await click('전체')
  await fill('#group-rounds-dialog input[aria-label="내가 참여한 회차 검색어"]', '')
  await waitFor("document.querySelectorAll('#group-rounds-dialog [aria-label=\"참여 회차 전체 목록\"] a.round-link').length === 4")
  await evaluate("document.querySelector('button[aria-label=\"참여 회차 목록 닫기\"]').click()")
  await waitFor("!document.querySelector('#group-rounds-dialog[open]')")
  console.log('PASS group round list keeps the latest three and searches or filters inside its dialog')
  await navigate(`/home/rounds/${roundId}`, '정산 확정')
  await click('정산 확정')
  await waitFor(hasText('기록 단계로 다시 열기'))
  await click('기록 단계로 다시 열기')
  await waitFor(hasText('정산 확정'))
  await click('정산 확정')
  await click('전송 안내 확인')
  await waitFor(hasText('랜덤 돌리기'))
  assert.equal(await evaluate("Boolean(document.querySelector('input[aria-label=\"공유 링크\"]'))"), false)
  await click('랜덤 돌리기')
  await waitFor("Boolean(document.querySelector('.copy-link input')?.value)")
  assert.equal(await evaluate("Boolean(document.querySelector('.copy-link button'))"), false)
  assert.equal(await evaluate("document.querySelector('.bank-details').textContent.includes('002222')"), true)
  assert.equal(await evaluate("Array.from(document.querySelectorAll('.bank-details')).some(dl => dl.textContent.includes('003333'))"), false)
  await withWriteTransaction(async client => {
    const result = await client.query(`UPDATE users SET bank_name='B새은행', account_number='000888',
      bank_updated_at=extract(epoch FROM now())::bigint, bank_version=bank_version+1
      WHERE id=$1 AND provider_subject=$2`, [payer.session.userId, payer.subject])
    assert.equal(result.rowCount, 1)
  })
  await click('최신 정보 새로고침')
  await waitFor("document.querySelector('.bank-details')?.textContent.includes('000888')")
  console.log('PASS settlement recipient shows the latest manually saved account')
  await mkdir(artifactDir, { recursive: true })
  const screenshot = await cdp('Page.captureScreenshot', { format: 'png', captureBeyondViewport: true })
  await writeFile(join(artifactDir, 'settlement.png'), Buffer.from(screenshot.data, 'base64'))
  assert.equal(await evaluate("(() => { const input = document.querySelector('.copy-link input'); input.focus(); return input.selectionStart === 0 && input.selectionEnd === input.value.length; })()"), true)
  const settlementVersion = (await api(owner.session, `/api/rounds/${roundId}/settlement`)).version
  await setSession(payer.session)
  await navigate(`/settlements/${roundId}`, '이 사람에게 받아요')
  const payerSettlement = await api(payer.session, `/api/rounds/${roundId}/settlement`)
  assert.equal(payerSettlement.version, settlementVersion)
  assert.equal(payerSettlement.incoming.length, 2)
  assert.equal(await evaluate("document.querySelectorAll('.settlement-receipt-toggle').length"), 2)
  assert.equal(await evaluate("document.querySelector('.settlement-animated-money').getAttribute('aria-label').replace(/\\D/g, '')"), settlementAmountMinor.toString())
  const firstIncomingMinor = BigInt(payerSettlement.incoming[0].amountMinor)
  const decreasedMinor = settlementAmountMinor - firstIncomingMinor
  await evaluate("document.querySelector('.settlement-receipt-toggle').click()")
  await waitFor("document.querySelector('.settlement-receipt-toggle')?.getAttribute('aria-pressed') === 'true'")
  await waitFor(`document.querySelector('.settlement-animated-money')?.getAttribute('aria-label')?.replace(/\\D/g, '') === '${decreasedMinor}' && Array.from(document.querySelectorAll('.settlement-money-digit-changing.roll-down')).some(digit => digit.getAnimations({ subtree: true }).some(animation => animation.playState === 'running'))`, 'receiving amount decrease digit animation')
  assert.equal(await evaluate("document.querySelector('.settlement-receipt-toggle .settlement-person > span:last-child').classList.contains('settlement-received-text')"), true)
  assert.equal(await evaluate("document.querySelector('.settlement-animated-money').getAttribute('aria-label').replace(/\\D/g, '')"), decreasedMinor.toString())
  await cdp('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'reduce' }] })
  await waitFor("matchMedia('(prefers-reduced-motion: reduce)').matches && !document.querySelector('.settlement-money-digit-changing')", 'reduced motion immediately finishes digit animation')
  await cdp('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'no-preference' }] })
  await waitFor("!matchMedia('(prefers-reduced-motion: reduce)').matches")
  await evaluate("document.querySelector('.settlement-receipt-toggle').click()")
  await waitFor("document.querySelector('.settlement-receipt-toggle')?.getAttribute('aria-pressed') === 'false'")
  await waitFor(`document.querySelector('.settlement-animated-money')?.getAttribute('aria-label')?.replace(/\\D/g, '') === '${settlementAmountMinor}' && Array.from(document.querySelectorAll('.settlement-money-digit-changing.roll-up')).some(digit => digit.getAnimations({ subtree: true }).some(animation => animation.playState === 'running'))`, 'receiving amount increase digit animation')
  assert.equal(await evaluate("document.querySelector('.settlement-animated-money').getAttribute('aria-label').replace(/\\D/g, '')"), settlementAmountMinor.toString())
  await waitFor("!document.querySelector('.settlement-money-digit-changing')", 'increase digit animation cleanup')
  await evaluate("document.querySelector('.settlement-check-all input[type=checkbox]').click()")
  await waitFor("document.querySelector('.settlement-check-all input[type=checkbox]')?.checked && Array.from(document.querySelectorAll('.settlement-receipt-toggle')).every(button => button.getAttribute('aria-pressed') === 'true')")
  await waitFor("document.querySelector('.settlement-animated-money')?.getAttribute('aria-label')?.replace(/\\D/g, '') === '0' && Array.from(document.querySelectorAll('.settlement-money-digit-changing.roll-down')).some(digit => digit.getAnimations({ subtree: true }).some(animation => animation.playState === 'running'))", '13,593 to zero digit animation')
  assert.deepEqual(await evaluate("Array.from(document.querySelectorAll('.settlement-money-digit-changing')).map(digit => [digit.dataset.place, digit.dataset.sequence])"), [
    ['4', '1,0'],
    ['3', '3,2,1,0'],
    ['2', '5,4,3,2,1,0'],
    ['1', '9,8,7,6,5,4,3,2,1,0'],
    ['0', '3,2,1,0'],
  ])
  assert.deepEqual(await evaluate("Array.from(document.querySelectorAll('.settlement-money-digit-disappearing')).map(digit => [digit.dataset.place, digit.getAnimations().find(animation => animation.animationName === 'settlement-digit-collapse').effect.getTiming().delay])"), [['4', 80], ['3', 240], ['2', 400], ['1', 720]])
  assert.equal(await evaluate("document.querySelector('.settlement-money-symbol-disappearing').getAnimations().find(animation => animation.animationName === 'settlement-symbol-collapse').effect.getTiming().delay"), 240)
  const placeBeforeCleanup = await evaluate("document.querySelector('.settlement-money-digit[data-place=\"0\"]').getBoundingClientRect().left")
  await evaluate("Promise.all(Array.from(document.querySelectorAll('.settlement-money-digit-changing')).flatMap(digit => digit.getAnimations({ subtree: true })).filter(animation => animation.animationName.startsWith('settlement-digit-roll-')).map(animation => animation.finished)).then(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))")
  assert.equal(await evaluate("Boolean(document.querySelector('.settlement-money-digit-changing'))"), false)
  assert.ok(await evaluate("document.querySelector('.settlement-money-digit[data-place=\"0\"]').getBoundingClientRect().left") < placeBeforeCleanup)
  assert.equal(await evaluate("document.querySelector('.settlement-animated-money').getAttribute('aria-label').replace(/\\D/g, '')"), '0')
  await evaluate("document.querySelector('.settlement-check-all input[type=checkbox]').click()")
  await waitFor("!document.querySelector('.settlement-check-all input[type=checkbox]')?.checked && Array.from(document.querySelectorAll('.settlement-receipt-toggle')).every(button => button.getAttribute('aria-pressed') === 'false')")
  await waitFor(`document.querySelector('.settlement-animated-money')?.getAttribute('aria-label')?.replace(/\\D/g, '') === '${settlementAmountMinor}' && Array.from(document.querySelectorAll('.settlement-money-digit-changing.roll-up')).some(digit => digit.getAnimations({ subtree: true }).some(animation => animation.playState === 'running'))`, 'zero to 13,593 digit animation')
  assert.equal(await evaluate("getComputedStyle(document.querySelector('.settlement-animated-money [data-anchor=\"3\"]')).visibility"), 'visible')
  await waitFor("!document.querySelector('.settlement-money-digit-changing')", 'zero to 13,593 digit animation cleanup')
  await evaluate("document.querySelector('.settlement-check-all input[type=checkbox]').click()")
  await waitFor("document.querySelector('.settlement-check-all input[type=checkbox]')?.checked")
  await setSession(owner.session)
  await navigate(`/settlements/${roundId}`, '정산 확인 현황')
  await waitFor(hasText('1/1명 완료'))
  await click('정산 종료')
  await waitFor("location.pathname === '/home/history'")
  await waitFor("Boolean(document.querySelector('input[aria-label=\"정산 기록 검색어\"]'))")
  assert.equal(await evaluate("Boolean(document.querySelector('.round-search-bar > svg') && document.querySelector('.round-search-bar > input[aria-label=\"정산 기록 검색어\"]'))"), true)
  assert.equal(await evaluate("(() => { const heading = document.querySelector('h1.topbar-title'); const search = document.querySelector('.round-search-bar'); const states = document.querySelector('[aria-label=\"회차 상태\"]'); return Boolean(heading?.textContent === '정산 기록' && search && states && (heading.compareDocumentPosition(search) & Node.DOCUMENT_POSITION_FOLLOWING) && (search.compareDocumentPosition(states) & Node.DOCUMENT_POSITION_FOLLOWING)); })()"), true)
  assert.equal(await evaluate("document.querySelectorAll('[aria-label=\"회차 상태\"] > button').length === 3 && Array.from(document.querySelectorAll('[aria-label=\"회차 상태\"] > button')).find(button => button.textContent.trim() === '전체')?.getAttribute('aria-pressed') === 'true'"), true)
  await fill('input[aria-label="정산 기록 검색어"]', '지출과 제외 검증')
  await waitFor("document.querySelectorAll('a.round-link').length === 1 && document.querySelector('a.round-link')?.textContent.includes('지출과 제외 검증')")
  await fill('input[aria-label="정산 기록 검색어"]', groupName)
  await waitFor(`document.querySelectorAll('a.round-link').length === 4 && Array.from(document.querySelectorAll('a.round-link')).every(link => link.textContent.includes(${JSON.stringify(groupName)}))`)
  await click('진행 중')
  await waitFor("document.querySelectorAll('a.round-link').length === 3 && Array.from(document.querySelectorAll('[aria-label=\"회차 상태\"] > button')).find(button => button.textContent.trim() === '진행 중')?.getAttribute('aria-pressed') === 'true'")
  await click('정산 종료')
  await waitFor("document.querySelectorAll('a.round-link').length === 1 && Array.from(document.querySelectorAll('[aria-label=\"회차 상태\"] > button')).find(button => button.textContent.trim() === '정산 종료')?.getAttribute('aria-pressed') === 'true'")
  await click('전체')
  await waitFor("document.querySelectorAll('a.round-link').length === 4 && Array.from(document.querySelectorAll('[aria-label=\"회차 상태\"] > button')).find(button => button.textContent.trim() === '전체')?.getAttribute('aria-pressed') === 'true'")
  console.log('PASS round history and group round searches match round and group names')
  await navigate(`/home/rounds/${roundId}`, '종료된 회차예요.')
  assert.equal(await evaluate("Array.from(document.querySelectorAll('button')).some(button => ['지출 추가', '수정', '정산 확정', '기록 단계로 다시 열기', '회차 전체 취소'].includes(button.textContent.trim()))"), false)
  console.log('PASS per-digit amount roll, transfer receipt toggle, strikethrough, remaining amount, bulk confirmation, completion read-only')

  await setSession(payer.session)
  await navigate('/home/history', '지출과 제외 검증')
  await navigate(`/settlements/${roundId}`, '이 사람에게 받아요')
  assert.equal(await evaluate("document.querySelectorAll('.bank-details').length"), 0)
  assert.equal(await evaluate("Array.from(document.querySelectorAll('.settlement-receipt-toggle')).every(button => button.disabled && button.getAttribute('aria-pressed') === 'true')"), true)
  assert.equal(await evaluate("document.querySelector('.settlement-check-all input[type=checkbox]').disabled"), true)
  assert.equal(await evaluate("document.querySelector('.settlement-animated-money').getAttribute('aria-label').replace(/\\D/g, '')"), '0')
  await navigate('/home/all', '계좌 설정')
  assert.equal(await evaluate("Boolean(document.querySelector('[name=accountNumber]'))"), false)
  await evaluate("document.querySelector('a[href=\"/home/account\"]').click()")
  await waitFor("location.pathname === '/home/account'")
  assert.equal(await evaluate("Boolean(document.querySelector('.account-profile'))"), true)
  await waitFor(hasText('계좌 수정하기'))
  await click('회원 탈퇴')
  await waitFor("location.pathname === '/'")
  payer.session = await signInKakao(payer.subject, { displayName: '검증 B', email: null, profileImageUrl: null })
  assert.equal(payer.session.purpose, 'onboarding')
  await setSession(payer.session)
  await navigate('/onboarding', '검증 B님, 다시 만나 반가워요')
  assert.deepEqual(await evaluate("Array.from(document.querySelectorAll('.onboarding-page button')).filter(button => button.getClientRects().length && !button.classList.contains('bank-select-trigger')).map(button => button.textContent.trim())"), ['재가입하기', '다른 카카오 계정으로 로그인', '뒤로가기'])
  await waitFor("Boolean(document.querySelector('[name=bankCode]'))")
  assert.equal(await evaluate("document.querySelectorAll('[name=bankCode], [name=accountNumber], [name=accountHolder]').length"), 3)
  assert.equal(await evaluate("Boolean(document.querySelector('[name=birthDate]'))"), false)
  const rejoining = await api(payer.session, '/api/me')
  assert.equal(rejoining.purpose, 'onboarding')
  assert.notEqual(rejoining.deletedAt, null)
  await fill('[name=accountNumber]', '0002223333')
  await fill('[name=bankCode]', '004')
  await fill('[name=accountHolder]', '검증 B')
  assert.equal(await evaluate("document.querySelector('form').checkValidity()"), true)
  await click('재가입하기')
  await waitFor("location.pathname === '/home'")
  const rejoined = await evaluate("fetch('/api/me', { headers: { Authorization: 'Bearer ' + localStorage.getItem('da_moa_access') } }).then(response => response.json()).then(result => ({ id: result.data.id, purpose: result.data.purpose, deletedAt: result.data.deletedAt, accountNumber: result.data.bankAccount.accountNumber, verifiedAt: result.data.bankAccount.verifiedAt }))")
  assert.deepEqual(rejoined, { id: payer.session.userId, purpose: 'app', deletedAt: null, accountNumber: '0002223333', verifiedAt: null })
  const retained = await withWriteTransaction(async client => {
    const memberships = await client.query('SELECT 1 FROM group_members WHERE user_id=$1 AND left_at IS NULL', [payer.session.userId])
    const history = await client.query('SELECT 1 FROM round_members WHERE user_id=$1 AND round_id=$2', [payer.session.userId, roundId])
    return { activeMemberships: memberships.rowCount, historicalParticipation: history.rowCount }
  })
  assert.deepEqual(retained, { activeMemberships: 0, historicalParticipation: 1 })
  assert.ok(dialogs.some(text => text.includes('이대로 사용자들에게 메시지를 전송할까요?')))
  assert.deepEqual(exceptions, [])
  console.log('PASS leaver history, soft withdrawal, manual rejoin, and no automatic membership restoration')

  await setSession(owner.session)
  const departureGroup = await api(owner.session, '/api/groups', 'POST', { name: `이탈·닫기 UI ${runId}` })
  const departureInvite = await api(owner.session, `/api/groups/${departureGroup.id}/invites`, 'POST', {})
  await setSession(participant.session)
  await navigate(departureInvite.sharePath, '초대 수락하고 참여하기')
  await click('초대 수락하고 참여하기')
  await waitFor(hasText('이미 참여 중인 모임이에요.'))
  await evaluate("document.querySelector('a.primary-button').click()")
  await waitFor(`location.pathname === '/home/groups/${departureGroup.id}' && ${hasText('현재 멤버 2명')}`)
  const memberDepartureReads = apiReads.length
  await click('모임 나가기')
  await waitFor("location.pathname === '/home/groups'")
  await waitFor(hasText('새 모임 만들기'))
  await new Promise(resolve => setTimeout(resolve, 700))
  assert.equal(apiReads.slice(memberDepartureReads).filter(path => path === '/api/groups').length, 1, 'one groups read after member departure')
  await setSession(owner.session)
  await navigate(`/home/groups/${departureGroup.id}`, '현재 멤버 1명')
  const creatorDepartureReads = apiReads.length
  await click('모임 없애기')
  await waitFor("location.pathname === '/home/groups'")
  await waitFor(hasText('새 모임 만들기'))
  await new Promise(resolve => setTimeout(resolve, 700))
  assert.equal(apiReads.slice(creatorDepartureReads).filter(path => path === '/api/groups').length, 1, 'one groups read after creator closure')
  await fill('input[aria-label="모임 검색어"]', `이탈·닫기 UI ${runId}`)
  await waitFor(hasText('검색 결과가 없어요.'))
  assert.deepEqual(exceptions, [])
  console.log('PASS Group UI member departure and creator closure')

  await navigate('/home/account', '로그아웃')
  await click('로그아웃')
  await waitFor("location.pathname === '/login'")
  assert.equal(await evaluate("localStorage.getItem('da_moa_access')"), null)
  assert.equal((await cdp('Network.getAllCookies')).cookies.some(cookie => cookie.name === REFRESH_TOKEN_COOKIE_NAME), false)
  console.log('PASS logout deletes local Access JWT and Refresh cookie')
  console.log(`Browser evidence: ${join(artifactDir, 'settlement.png')}`)
} finally {
  ws.close()
  await fetch(`${debuggerOrigin}/json/close/${tab.id}`).catch(() => {})
}
