import type { ErrorCode } from '../../../../shared/appError'
export enum SettleErrorCode {
  VERSION_REQUIRED = 'invalid_version',
  ROUND_CREATION_KEY_REQUIRED = 'invalid_request_key',
  GROUP_MEMBERS_REQUIRED = 'invalid_participants',
  UNSUPPORTED_EXPENSE_CURRENCY = 'unsupported_currency',
  CURRENCY_CHANGE_REQUIRES_AMOUNT = 'invalid_amount',
  CURRENCY_CHANGE_REQUIRES_CUSTOM_SHARES = 'invalid_amount',
  INVALID_AMOUNT = 'invalid_amount',
  EXPENSE_AMOUNT_LIMIT_EXCEEDED = 'expense_amount_limit_exceeded',
  INVALID_SPLIT_MODE = 'invalid_participants',
  CUSTOM_SHARES_REQUIRE_CUSTOM_MODE = 'invalid_input',
  CUSTOM_SHARES_REQUIRED = 'invalid_participants',
  INVALID_CUSTOM_SHARE_AMOUNT = 'invalid_amount',
  PAYER_NOT_PARTICIPATING = 'invalid_participants',
  ALL_PARTICIPANTS_ARE_SERVER_SELECTED = 'invalid_participants',
  CUSTOM_PARTICIPANTS_REQUIRE_SHARES = 'invalid_input',
  INACTIVE_SHARE_PARTICIPANT = 'invalid_participants',
  PARTICIPANTS_REQUIRED = 'invalid_participants',
  CURRENCY_LIMIT_EXCEEDED = 'round_currency_limit_exceeded',
  ROUND_TOTAL_LIMIT_EXCEEDED = 'round_total_limit_exceeded',
  INVALID_PARTICIPANTS = 'invalid_participants',
  CHECK_STATE_REQUIRED = 'invalid_input',
  INVALID_SENDER = 'invalid_input',
  UNSUPPORTED_TRANSFER_CURRENCY = 'unsupported_currency',
  TRANSFER_CURRENCY_REQUIRED = 'unsupported_currency',
  FORBIDDEN_REQUEST = 'forbidden',
  INVALID_RECEIPT_FORM = 'invalid_input',
  SINGLE_RECEIPT_REQUIRED = 'invalid_input',
  API_NOT_FOUND = 'not_found',
  RESOURCE_NOT_FOUND = 'not_found',
  ROUND_ALREADY_EXISTS = 'round_already_exists',
  RECEIPT_TOO_LARGE = 'receipt_too_large',
  UNSUPPORTED_RECEIPT_TYPE = 'unsupported_receipt_type',
  CREATOR_ONLY = 'forbidden',
  INVALID_ROUND_STATE = 'invalid_round_state',
  STALE_ROUND = 'stale_round',
  MINIMUM_PARTICIPANTS = 'minimum_participants',
  UNAUTHORIZED = 'unauthorized',
  EXPENSE_EDITOR_ONLY = 'forbidden',
  INSUFFICIENT_PARTICIPANTS = 'minimum_participants',
  EMPTY_EXPENSES = 'empty_expenses',
  PENDING_REMAINDER = 'invalid_round_state',
  IDEMPOTENCY_CONFLICT = 'idempotency_conflict',
  PENDING_SETTLEMENT_CHECKS = 'pending_settlement_checks',
  ROUND_HAS_EXPENSES = 'round_has_expenses',
  UNFINALIZED_SETTLEMENT = 'invalid_round_state',
  NO_RECEIVABLE_TRANSFERS = 'forbidden',
  TRANSFER_NOT_FOUND = 'not_found',
  RECEIPT_PENDING = 'receipt_pending',
  STORAGE_UNAVAILABLE = 'storage_unavailable',
}
export const settleErrors = {
  VERSION_REQUIRED: { status: 400, code: SettleErrorCode.VERSION_REQUIRED, message: "회차 버전이 필요합니다", detail: null },
  ROUND_CREATION_KEY_REQUIRED: { status: 400, code: SettleErrorCode.ROUND_CREATION_KEY_REQUIRED, message: "UUIDv7 회차 생성 ticket이 필요합니다", detail: null },
  GROUP_MEMBERS_REQUIRED: { status: 400, code: SettleErrorCode.GROUP_MEMBERS_REQUIRED, message: "현재 모임 참여자만 선택할 수 있어요", detail: null },
  UNSUPPORTED_EXPENSE_CURRENCY: { status: 400, code: SettleErrorCode.UNSUPPORTED_EXPENSE_CURRENCY, message: "지원하는 지출 통화를 선택해 주세요", detail: null },
  CURRENCY_CHANGE_REQUIRES_AMOUNT: { status: 400, code: SettleErrorCode.CURRENCY_CHANGE_REQUIRES_AMOUNT, message: "통화를 변경할 때 금액을 다시 입력해 주세요", detail: null },
  CURRENCY_CHANGE_REQUIRES_CUSTOM_SHARES: { status: 400, code: SettleErrorCode.CURRENCY_CHANGE_REQUIRES_CUSTOM_SHARES, message: "통화를 변경할 때 개별 부담금을 다시 입력해 주세요", detail: null },
  INVALID_AMOUNT: { status: 400, code: SettleErrorCode.INVALID_AMOUNT, message: "통화에 맞는 양의 금액을 정확히 입력해 주세요", detail: null },
  EXPENSE_AMOUNT_LIMIT_EXCEEDED: { status: 400, code: SettleErrorCode.EXPENSE_AMOUNT_LIMIT_EXCEEDED, message: '입력값을 확인해 주세요', detail: null },
  INVALID_SPLIT_MODE: { status: 400, code: SettleErrorCode.INVALID_SPLIT_MODE, message: "분배 방식을 선택해 주세요", detail: null },
  CUSTOM_SHARES_REQUIRE_CUSTOM_MODE: { status: 400, code: SettleErrorCode.CUSTOM_SHARES_REQUIRE_CUSTOM_MODE, message: "개별 부담금은 개별 항목 분배에서만 입력해 주세요", detail: null },
  CUSTOM_SHARES_REQUIRED: { status: 400, code: SettleErrorCode.CUSTOM_SHARES_REQUIRED, message: "부담자와 부담금을 선택해 주세요", detail: null },
  INVALID_CUSTOM_SHARE_AMOUNT: { status: 400, code: SettleErrorCode.INVALID_CUSTOM_SHARE_AMOUNT, message: "통화에 맞는 양의 부담금을 정확히 입력해 주세요", detail: null },
  PAYER_NOT_PARTICIPATING: { status: 400, code: SettleErrorCode.PAYER_NOT_PARTICIPATING, message: "결제자는 이번 회차 참여자여야 합니다", detail: null },
  ALL_PARTICIPANTS_ARE_SERVER_SELECTED: { status: 400, code: SettleErrorCode.ALL_PARTICIPANTS_ARE_SERVER_SELECTED, message: "전체 분배의 참여자는 서버에서 결정합니다", detail: null },
  CUSTOM_PARTICIPANTS_REQUIRE_SHARES: { status: 400, code: SettleErrorCode.CUSTOM_PARTICIPANTS_REQUIRE_SHARES, message: "개별 항목 분배의 부담자는 부담금과 함께 선택해 주세요", detail: null },
  INACTIVE_SHARE_PARTICIPANT: { status: 400, code: SettleErrorCode.INACTIVE_SHARE_PARTICIPANT, message: "부담자는 제외되지 않은 회차 참여자여야 합니다", detail: null },
  PARTICIPANTS_REQUIRED: { status: 400, code: SettleErrorCode.PARTICIPANTS_REQUIRED, message: "부담자가 필요합니다", detail: null },
  CURRENCY_LIMIT_EXCEEDED: { status: 400, code: SettleErrorCode.CURRENCY_LIMIT_EXCEEDED, message: "한 회차에는 최대 5개 통화를 기록할 수 있어요", detail: null },
  ROUND_TOTAL_LIMIT_EXCEEDED: { status: 400, code: SettleErrorCode.ROUND_TOTAL_LIMIT_EXCEEDED, message: '입력값을 확인해 주세요', detail: null },
  INVALID_PARTICIPANTS: { status: 400, code: SettleErrorCode.INVALID_PARTICIPANTS, message: "지출 참여 내역을 다시 확인해 주세요", detail: null },
  CHECK_STATE_REQUIRED: { status: 400, code: SettleErrorCode.CHECK_STATE_REQUIRED, message: "정산 확인 여부를 선택해 주세요", detail: null },
  INVALID_SENDER: { status: 400, code: SettleErrorCode.INVALID_SENDER, message: "확인할 송금자를 다시 선택해 주세요", detail: null },
  UNSUPPORTED_TRANSFER_CURRENCY: { status: 400, code: SettleErrorCode.UNSUPPORTED_TRANSFER_CURRENCY, message: "지원하는 통화를 선택해 주세요", detail: null },
  TRANSFER_CURRENCY_REQUIRED: { status: 400, code: SettleErrorCode.TRANSFER_CURRENCY_REQUIRED, message: "개별 수취 확인에는 통화가 필요합니다", detail: null },
  FORBIDDEN_REQUEST: { status: 403, code: SettleErrorCode.FORBIDDEN_REQUEST, message: "허용되지 않은 요청입니다", detail: null },
  INVALID_RECEIPT_FORM: { status: 400, code: SettleErrorCode.INVALID_RECEIPT_FORM, message: "영수증 업로드 형식을 확인해 주세요", detail: null },
  SINGLE_RECEIPT_REQUIRED: { status: 400, code: SettleErrorCode.SINGLE_RECEIPT_REQUIRED, message: "이미지를 한 개씩 올려 주세요", detail: null },
  API_NOT_FOUND: { status: 404, code: SettleErrorCode.API_NOT_FOUND, message: "요청한 API를 찾을 수 없어요", detail: null },
  RESOURCE_NOT_FOUND: { status: 404, code: SettleErrorCode.RESOURCE_NOT_FOUND, message: "요청한 자료를 찾을 수 없어요", detail: null },
  ROUND_ALREADY_EXISTS: { status: 409, code: SettleErrorCode.ROUND_ALREADY_EXISTS, message: "이미 생성된 회차입니다. 회차 목록을 확인해 주세요", detail: null },
  RECEIPT_TOO_LARGE: { status: 413, code: SettleErrorCode.RECEIPT_TOO_LARGE, message: "영수증 파일은 10MB 이하로 올려 주세요", detail: null },
  UNSUPPORTED_RECEIPT_TYPE: { status: 415, code: SettleErrorCode.UNSUPPORTED_RECEIPT_TYPE, message: "AVIF 이미지 파일을 선택해 주세요", detail: null },
  CREATOR_ONLY: { status: 403, code: SettleErrorCode.CREATOR_ONLY, message: "회차 생성자만 할 수 있어요", detail: null },
  INVALID_ROUND_STATE: { status: 409, code: SettleErrorCode.INVALID_ROUND_STATE, message: "현재 회차 상태에서는 할 수 없어요. 최신 상태를 확인해 주세요", detail: null },
  STALE_ROUND: { status: 409, code: SettleErrorCode.STALE_ROUND, message: "다른 변경이 먼저 저장됐어요. 최신 내역을 확인해 주세요", detail: null },
  MINIMUM_PARTICIPANTS: { status: 409, code: SettleErrorCode.MINIMUM_PARTICIPANTS, message: "회차 생성자를 포함해 최소 2명을 선택해 주세요", detail: null },
  UNAUTHORIZED: { status: 401, code: SettleErrorCode.UNAUTHORIZED, message: "로그인이 필요합니다", detail: null },
  EXPENSE_EDITOR_ONLY: { status: 403, code: SettleErrorCode.EXPENSE_EDITOR_ONLY, message: "지출 작성자 또는 회차 생성자만 수정할 수 있어요", detail: null },
  INSUFFICIENT_PARTICIPANTS: { status: 409, code: SettleErrorCode.INSUFFICIENT_PARTICIPANTS, message: "회차는 최소 2명이어야 합니다", detail: null },
  EMPTY_EXPENSES: { status: 409, code: SettleErrorCode.EMPTY_EXPENSES, message: "지출 내역이 없습니다", detail: null },
  PENDING_REMAINDER: { status: 409, code: SettleErrorCode.PENDING_REMAINDER, message: "나머지 배분을 먼저 완료해 주세요", detail: null },
  IDEMPOTENCY_CONFLICT: { status: 409, code: SettleErrorCode.IDEMPOTENCY_CONFLICT, message: "같은 요청 키로 다른 내용을 저장할 수 없어요", detail: null },
  PENDING_SETTLEMENT_CHECKS: { status: 409, code: SettleErrorCode.PENDING_SETTLEMENT_CHECKS, message: "모든 수취인이 입금을 확인한 뒤 종료할 수 있어요", detail: null },
  ROUND_HAS_EXPENSES: { status: 409, code: SettleErrorCode.ROUND_HAS_EXPENSES, message: "지출 기록이 있는 회차는 취소할 수 없어요. 지출을 먼저 삭제해 주세요", detail: null },
  UNFINALIZED_SETTLEMENT: { status: 409, code: SettleErrorCode.UNFINALIZED_SETTLEMENT, message: "최종 금액이 정해진 뒤 확인할 수 있어요", detail: null },
  NO_RECEIVABLE_TRANSFERS: { status: 403, code: SettleErrorCode.NO_RECEIVABLE_TRANSFERS, message: "확인할 수 있는 수취 내역이 없어요", detail: null },
  TRANSFER_NOT_FOUND: { status: 404, code: SettleErrorCode.TRANSFER_NOT_FOUND, message: "변경할 수취 내역이 없어요", detail: null },
  RECEIPT_PENDING: { status: 409, code: SettleErrorCode.RECEIPT_PENDING, message: "영수증을 저장하고 있어요", detail: null },
  STORAGE_UNAVAILABLE: { status: 503, code: SettleErrorCode.STORAGE_UNAVAILABLE, message: "영수증 저장에 실패했어요. 삭제 후 다시 올려 주세요", detail: null },
} satisfies Record<string, ErrorCode>
